insert into public.peliculas (nombre, imagen, sinopsis, estreno) values
  ('Interstellar', 'https://www.themoviedb.org/t/p/w600_and_h900_face/cQuuBjG78j4b2r1dFpAjnjbUplv.jpg', 'Un grupo de exploradores viaja a traves de un agujero de gusano en busca de un nuevo hogar para la humanidad.', 2014),
  ('Inception', 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg', 'Un ladron experto en robar secretos del subconsciente recibe la tarea de plantar una idea en la mente de alguien.', 2010),
  ('The Matrix', 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', 'Un programador descubre que la realidad es una simulacion controlada por maquinas y se une a la resistencia.', 1999),
  ('Pulp Fiction', 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', 'Historias interconectadas de gangsters, un boxeador y una pareja de ladrones en el Los Angeles criminal.', 1994),
  ('The Godfather', 'https://www.themoviedb.org/t/p/w600_and_h900_face/5HlLUsmsv60cZVTzVns9ICZD6zU.jpg', 'El patriarca de una familia mafiosa transfiere el control de su imperio a su hijo menor.', 1972),
  ('Forrest Gump', 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', 'Un hombre de Alabama con bajas capacidades intelectuales vive eventos historicos clave del siglo XX.', 1994),
  ('The Dark Knight', 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'Batman enfrenta al Joker, un criminal caotico que amenaza con hundir Gotham en la anarquia.', 2008),
  ('Fight Club', 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', 'Un insomne y un vendedor de jabon crean un club de lucha clandestino que deriva en algo mucho mas oscuro.', 1999),
  ('Parasite', 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'Una familia pobre se infiltra en la vida de una adinerada familia de Seoul con consecuencias impredecibles.', 2019),
  ('Whiplash', 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg', 'Un joven baterista ambicioso es llevado al limite por un instructor de musica obsesivo y despiadado.', 2014),
  ('Coco', 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg', 'Un nino viaja al mundo de los muertos para descubrir los secretos de su familia y su pasion por la musica.', 2017),
  ('Spirited Away', 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'Una nina queda atrapada en un mundo espiritista y debe trabajar en un bano magico para rescatar a sus padres.', 2001),
  ('The Shawshank Redemption', 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', 'Un banquero inocente encarcelado forge una amistad especial mientras busca recuperar su libertad.', 1994),
  ('Gladiator', 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg', 'Un general romano traicionado se convierte en gladiador y busca venganza contra el corrupto emperador.', 2000),
  ('Titanic', 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', 'Una historia de amor entre dos jovenes de clases distintas a bordo del transatlantico Titanic.', 1997),
  ('Avatar', 'https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg', 'Un marine paraplejico viaja a Pandora, un exuberante planeta extraterrestre en conflicto con los humanos.', 2009),
  ('Joker', 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', 'Arthur Fleck, un comico fracasado en Gotham, va perdiendo la cordura hasta convertirse en el Joker.', 2019),
  ('La La Land', 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg', 'Una actriz aspirante y un musico de jazz se enamoran en Los Angeles mientras persiguen sus suenos.', 2016),
  ('Get Out', 'https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg', 'Un hombre afroamericano descubre oscuros secretos cuando visita a la familia de su novia blanca.', 2017),
  ('Everything Everywhere All at Once', 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg', 'Una lavandera descubre que puede acceder a vidas de universos paralelos y debe salvar el multiverso.', 2022);
